# Generated by Django 5.2.4 on 2025-07-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_room_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='equipment',
            field=models.ManyToManyField(blank=True, null=True, related_name='rooms', to='booking.equipment'),
        ),
    ]
