# Generated by Django 5.2.4 on 2025-07-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_equipment_room_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='booking.equipment'),
        ),
    ]
