# Generated by Django 5.2.4 on 2025-07-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_room_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='equipment',
            field=models.ManyToManyField(related_name='rooms', to='booking.equipment'),
        ),
    ]
