# Generated by Django 5.2.4 on 2025-07-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_room_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='reserved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
