# Generated by Django 5.2.4 on 2025-07-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_room_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
